# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to default.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Boot configuration
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # File systems configuration
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/xxxx-xxxx";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Example for separate home partition
  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
  #     fsType = "ext4";
  #   };

  # Example for BTRFS with subvolumes
  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
  #     fsType = "btrfs";
  #     options = [ "subvol=@" "compress=zstd" "noatime" ];
  #   };
  # 
  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
  #     fsType = "btrfs";
  #     options = [ "subvol=@home" "compress=zstd" "noatime" ];
  #   };
  # 
  # fileSystems."/nix" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
  #     fsType = "btrfs";
  #     options = [ "subvol=@nix" "compress=zstd" "noatime" ];
  #   };

  # Swap configuration
  swapDevices = [ ];
  
  # Example swap file
  # swapDevices = [
  #   { device = "/var/lib/swapfile";
  #     size = 16384; # 16GB
  #   }
  # ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  
  # Hardware-specific configuration
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Graphics configuration (choose appropriate for your hardware)
  # Intel graphics
  # hardware.graphics.extraPackages = with pkgs; [
  #   intel-media-driver
  #   vaapiIntel
  #   vaapiVdpau
  #   libvdpau-va-gl
  # ];
  
  # AMD graphics
  # hardware.graphics.extraPackages = with pkgs; [
  #   rocm-opencl-icd
  #   rocm-opencl-runtime
  #   amdvlk
  # ];
  # hardware.graphics.extraPackages32 = with pkgs.pkgsi686Linux; [
  #   amdvlk
  # ];
  
  # NVIDIA graphics
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  #   powerManagement.finegrained = false;
  #   open = false;
  #   nvidiaSettings = true;
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  # };
  # services.xserver.videoDrivers = [ "nvidia" ];
  
  # High-DPI configuration
  # hardware.video.hidpi.enable = lib.mkDefault true;
  
  # Power management for laptops
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}